services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
       - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
       - ./monitoring:/etc/prometheus:ro
    ports:
      - "9090:9090"
    restart: always
    networks:
      - reference_network


  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml

    networks:
      - reference_network


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      - reference_network


  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/config.yml
      - ./monitoring/loki-data:/loki
    networks:
      - reference_network

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    restart: always
    volumes:
      - ./logs:/app/logs            
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - reference_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"  # UI
      - "4318:4318" 
    networks:
      - reference_network


volumes:
  grafana-storage:

networks:
  reference_network:
    external: true
